id = "ayml"
name = "AYML"
version = "0.0.1"
schema_version = 1
authors = ["Alex <alex@ashell.dev>"]
description = "AYML language support for Zed"

[grammars.ayml]
repository = "file:///Users/alex/Projects/ayml/tree-sitter-ayml"
rev = "1bfc85c7b7170760b6cee8ffc91ed9bf466fa924"

[language_servers.ayml-lsp]
name = "ayml-lsp"
languages = ["AYML"]
