id = "ayml"
name = "AYML"
version = "0.0.1"
schema_version = 1
authors = ["Alex <alex@ashell.dev>"]
description = "AYML language support for Zed"

[grammars.ayml]
repository = "file:///Users/alex/Projects/ayml/tree-sitter-ayml"
rev = "9cdf3987dcc5511ebcab0e8a62141db095a7e6e8"

[language_servers.ayml-lsp]
name = "ayml-lsp"
languages = ["AYML"]
