/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 37
#define LARGE_STATE_COUNT 20
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__newline = 1,
  sym_comment = 2,
  sym_mapping_key = 3,
  sym_sequence_indicator = 4,
  anon_sym_null = 5,
  anon_sym_true = 6,
  anon_sym_false = 7,
  sym_float_literal = 8,
  sym_integer_literal = 9,
  sym_double_quoted_string = 10,
  sym_triple_quoted_string = 11,
  sym_bare_string = 12,
  anon_sym_LBRACK = 13,
  anon_sym_COMMA = 14,
  anon_sym_RBRACK = 15,
  anon_sym_LBRACE = 16,
  anon_sym_RBRACE = 17,
  sym_flow_bare_string = 18,
  sym_document = 19,
  sym__statement = 20,
  sym_mapping_pair = 21,
  sym_sequence_entry = 22,
  sym__scalar = 23,
  sym_null_literal = 24,
  sym_boolean_literal = 25,
  sym_flow_sequence = 26,
  sym_flow_mapping = 27,
  sym_flow_pair = 28,
  sym__flow_value = 29,
  aux_sym_document_repeat1 = 30,
  aux_sym_flow_sequence_repeat1 = 31,
  aux_sym_flow_mapping_repeat1 = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__newline] = "_newline",
  [sym_comment] = "comment",
  [sym_mapping_key] = "mapping_key",
  [sym_sequence_indicator] = "sequence_indicator",
  [anon_sym_null] = "null",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_float_literal] = "float_literal",
  [sym_integer_literal] = "integer_literal",
  [sym_double_quoted_string] = "double_quoted_string",
  [sym_triple_quoted_string] = "triple_quoted_string",
  [sym_bare_string] = "bare_string",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_flow_bare_string] = "flow_bare_string",
  [sym_document] = "document",
  [sym__statement] = "_statement",
  [sym_mapping_pair] = "mapping_pair",
  [sym_sequence_entry] = "sequence_entry",
  [sym__scalar] = "_scalar",
  [sym_null_literal] = "null_literal",
  [sym_boolean_literal] = "boolean_literal",
  [sym_flow_sequence] = "flow_sequence",
  [sym_flow_mapping] = "flow_mapping",
  [sym_flow_pair] = "flow_pair",
  [sym__flow_value] = "_flow_value",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_flow_sequence_repeat1] = "flow_sequence_repeat1",
  [aux_sym_flow_mapping_repeat1] = "flow_mapping_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__newline] = sym__newline,
  [sym_comment] = sym_comment,
  [sym_mapping_key] = sym_mapping_key,
  [sym_sequence_indicator] = sym_sequence_indicator,
  [anon_sym_null] = anon_sym_null,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_float_literal] = sym_float_literal,
  [sym_integer_literal] = sym_integer_literal,
  [sym_double_quoted_string] = sym_double_quoted_string,
  [sym_triple_quoted_string] = sym_triple_quoted_string,
  [sym_bare_string] = sym_bare_string,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_flow_bare_string] = sym_flow_bare_string,
  [sym_document] = sym_document,
  [sym__statement] = sym__statement,
  [sym_mapping_pair] = sym_mapping_pair,
  [sym_sequence_entry] = sym_sequence_entry,
  [sym__scalar] = sym__scalar,
  [sym_null_literal] = sym_null_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym_flow_sequence] = sym_flow_sequence,
  [sym_flow_mapping] = sym_flow_mapping,
  [sym_flow_pair] = sym_flow_pair,
  [sym__flow_value] = sym__flow_value,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_flow_sequence_repeat1] = aux_sym_flow_sequence_repeat1,
  [aux_sym_flow_mapping_repeat1] = aux_sym_flow_mapping_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_mapping_key] = {
    .visible = true,
    .named = true,
  },
  [sym_sequence_indicator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_float_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_triple_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_bare_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_flow_bare_string] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_mapping_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_sequence_entry] = {
    .visible = true,
    .named = true,
  },
  [sym__scalar] = {
    .visible = false,
    .named = true,
  },
  [sym_null_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_flow_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_flow_mapping] = {
    .visible = true,
    .named = true,
  },
  [sym_flow_pair] = {
    .visible = true,
    .named = true,
  },
  [sym__flow_value] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_flow_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_flow_mapping_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_value = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_value, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '\n', 12,
        '\r', 1,
        '"', 4,
        '#', 13,
        '+', 45,
        ',', 94,
        '-', 15,
        '0', 33,
        '[', 93,
        ']', 95,
        'f', 47,
        'i', 63,
        'n', 49,
        't', 67,
        '{', 96,
        '}', 97,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < 'A' || ']' < lookahead)) ADVANCE(87);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(12);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 12,
        '\r', 1,
        '"', 4,
        '+', 46,
        '-', 46,
        '0', 35,
        '[', 93,
        'f', 48,
        'i', 65,
        'n', 50,
        't', 68,
        '{', 96,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '#' &&
          (lookahead < '+' || '-' < lookahead) &&
          (lookahead < 'A' || ']' < lookahead) &&
          lookahead != '}') ADVANCE(92);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '\n', 12,
        '\r', 1,
        '"', 4,
        '+', 98,
        ',', 94,
        '-', 98,
        '0', 37,
        '[', 93,
        ']', 95,
        'f', 99,
        'i', 108,
        'n', 100,
        't', 109,
        '{', 96,
        '}', 97,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '#' &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(118);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(43);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(44);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(6);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(7);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '\n', 12,
        '\r', 1,
        '"', 4,
        '#', 13,
        '+', 46,
        ',', 94,
        '-', 16,
        '0', 35,
        '[', 93,
        ']', 95,
        'f', 48,
        'i', 65,
        'n', 50,
        't', 68,
        '{', 96,
        '}', 97,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(10);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < 'A' || ']' < lookahead)) ADVANCE(92);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_mapping_key);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_sequence_indicator);
      if (lookahead == '0') ADVANCE(33);
      if (lookahead == 'i') ADVANCE(77);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_sequence_indicator);
      if (lookahead == '0') ADVANCE(35);
      if (lookahead == 'i') ADVANCE(78);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_null);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_null);
      if (lookahead == ':') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_null);
      if (lookahead == ':') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == ':') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == ':') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == ':') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == ':') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_float_literal);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_float_literal);
      if (lookahead == ':') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_float_literal);
      if (lookahead == ':') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_float_literal);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_float_literal);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_float_literal);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_float_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(84);
      if (lookahead == 'b') ADVANCE(81);
      if (lookahead == 'o') ADVANCE(83);
      if (lookahead == 'x') ADVANCE(86);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(84);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(90);
      if (lookahead == 'b') ADVANCE(82);
      if (lookahead == 'o') ADVANCE(88);
      if (lookahead == 'x') ADVANCE(91);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(90);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(116);
      if (lookahead == 'b') ADVANCE(113);
      if (lookahead == 'o') ADVANCE(114);
      if (lookahead == 'x') ADVANCE(117);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(116);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_integer_literal);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_integer_literal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_double_quoted_string);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_double_quoted_string);
      if (lookahead == '"') ADVANCE(8);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_triple_quoted_string);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == '0') ADVANCE(33);
      if (lookahead == 'i') ADVANCE(77);
      if (lookahead == ',' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(92);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(87);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == '0') ADVANCE(35);
      if (lookahead == 'i') ADVANCE(78);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(92);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'a') ADVANCE(57);
      if (lookahead == ',' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(87);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'a') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(92);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'a') ADVANCE(64);
      if (lookahead == 'u') ADVANCE(61);
      if (lookahead == ',' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(87);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'a') ADVANCE(66);
      if (lookahead == 'u') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(92);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'e') ADVANCE(21);
      if (lookahead == ',' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(87);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'e') ADVANCE(24);
      if (lookahead == ',' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(87);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'e') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(92);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'e') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(92);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'f') ADVANCE(27);
      if (lookahead == ',' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(87);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'f') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(92);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'l') ADVANCE(69);
      if (lookahead == ',' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(87);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'l') ADVANCE(18);
      if (lookahead == ',' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(87);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'l') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(92);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'l') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(92);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'l') ADVANCE(58);
      if (lookahead == ',' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(87);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'l') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(92);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'n') ADVANCE(55);
      if (lookahead == ',' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(87);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'n') ADVANCE(27);
      if (lookahead == ',' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(87);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'n') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(92);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'n') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(92);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'r') ADVANCE(71);
      if (lookahead == ',' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(87);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'r') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(92);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 's') ADVANCE(52);
      if (lookahead == ',' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(87);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 's') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(92);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'u') ADVANCE(51);
      if (lookahead == ',' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(87);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'u') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(92);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == ',' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(87);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ':') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(92);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 'f') ADVANCE(26);
      if (lookahead == ',' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(87);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 'f') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(92);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 'n') ADVANCE(75);
      if (lookahead == ',' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(87);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == 'n') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(92);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(85);
      if (lookahead == ',' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(87);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(92);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(39);
      if (lookahead == ',' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(87);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(92);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ',' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(87);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ',' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(87);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ',' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(87);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ',' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(87);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead == ',' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_bare_string);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(92);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_bare_string);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(92);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_bare_string);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(92);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_bare_string);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(92);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_bare_string);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_flow_bare_string);
      if (lookahead == '0') ADVANCE(37);
      if (lookahead == 'i') ADVANCE(108);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(118);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_flow_bare_string);
      if (lookahead == 'a') ADVANCE(104);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(118);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_flow_bare_string);
      if (lookahead == 'a') ADVANCE(107);
      if (lookahead == 'u') ADVANCE(106);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(118);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_flow_bare_string);
      if (lookahead == 'e') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(118);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_flow_bare_string);
      if (lookahead == 'e') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(118);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_flow_bare_string);
      if (lookahead == 'f') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(118);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_flow_bare_string);
      if (lookahead == 'l') ADVANCE(110);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(118);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_flow_bare_string);
      if (lookahead == 'l') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(118);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_flow_bare_string);
      if (lookahead == 'l') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(118);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_flow_bare_string);
      if (lookahead == 'n') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(118);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_flow_bare_string);
      if (lookahead == 'n') ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(118);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_flow_bare_string);
      if (lookahead == 'r') ADVANCE(111);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(118);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_flow_bare_string);
      if (lookahead == 's') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(118);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_flow_bare_string);
      if (lookahead == 'u') ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(118);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_flow_bare_string);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(115);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          (lookahead < '+' || '-' < lookahead) &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(118);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_flow_bare_string);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(118);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_flow_bare_string);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(118);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_flow_bare_string);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(118);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_flow_bare_string);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(118);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_flow_bare_string);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(118);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_flow_bare_string);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ',' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(118);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 10},
  [2] = {.lex_state = 10},
  [3] = {.lex_state = 10},
  [4] = {.lex_state = 10},
  [5] = {.lex_state = 10},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 10},
  [8] = {.lex_state = 10},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 10},
  [11] = {.lex_state = 10},
  [12] = {.lex_state = 10},
  [13] = {.lex_state = 10},
  [14] = {.lex_state = 10},
  [15] = {.lex_state = 10},
  [16] = {.lex_state = 10},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 10},
  [22] = {.lex_state = 10},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 10},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 10},
  [31] = {.lex_state = 10},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 10},
  [36] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__newline] = ACTIONS(3),
    [sym_comment] = ACTIONS(1),
    [sym_mapping_key] = ACTIONS(1),
    [sym_sequence_indicator] = ACTIONS(1),
    [anon_sym_null] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_float_literal] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [sym_double_quoted_string] = ACTIONS(1),
    [sym_triple_quoted_string] = ACTIONS(1),
    [sym_bare_string] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_flow_bare_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(36),
    [sym__statement] = STATE(2),
    [sym_mapping_pair] = STATE(2),
    [sym_sequence_entry] = STATE(2),
    [sym__scalar] = STATE(2),
    [sym_null_literal] = STATE(2),
    [sym_boolean_literal] = STATE(2),
    [sym_flow_sequence] = STATE(2),
    [sym_flow_mapping] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym__newline] = ACTIONS(3),
    [sym_comment] = ACTIONS(7),
    [sym_mapping_key] = ACTIONS(9),
    [sym_sequence_indicator] = ACTIONS(11),
    [anon_sym_null] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [sym_float_literal] = ACTIONS(17),
    [sym_integer_literal] = ACTIONS(17),
    [sym_double_quoted_string] = ACTIONS(17),
    [sym_triple_quoted_string] = ACTIONS(7),
    [sym_bare_string] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
  },
  [STATE(2)] = {
    [sym__statement] = STATE(3),
    [sym_mapping_pair] = STATE(3),
    [sym_sequence_entry] = STATE(3),
    [sym__scalar] = STATE(3),
    [sym_null_literal] = STATE(3),
    [sym_boolean_literal] = STATE(3),
    [sym_flow_sequence] = STATE(3),
    [sym_flow_mapping] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym__newline] = ACTIONS(3),
    [sym_comment] = ACTIONS(25),
    [sym_mapping_key] = ACTIONS(9),
    [sym_sequence_indicator] = ACTIONS(11),
    [anon_sym_null] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [sym_float_literal] = ACTIONS(27),
    [sym_integer_literal] = ACTIONS(27),
    [sym_double_quoted_string] = ACTIONS(27),
    [sym_triple_quoted_string] = ACTIONS(25),
    [sym_bare_string] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(3),
    [sym_mapping_pair] = STATE(3),
    [sym_sequence_entry] = STATE(3),
    [sym__scalar] = STATE(3),
    [sym_null_literal] = STATE(3),
    [sym_boolean_literal] = STATE(3),
    [sym_flow_sequence] = STATE(3),
    [sym_flow_mapping] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym__newline] = ACTIONS(3),
    [sym_comment] = ACTIONS(31),
    [sym_mapping_key] = ACTIONS(34),
    [sym_sequence_indicator] = ACTIONS(37),
    [anon_sym_null] = ACTIONS(40),
    [anon_sym_true] = ACTIONS(43),
    [anon_sym_false] = ACTIONS(43),
    [sym_float_literal] = ACTIONS(46),
    [sym_integer_literal] = ACTIONS(46),
    [sym_double_quoted_string] = ACTIONS(46),
    [sym_triple_quoted_string] = ACTIONS(31),
    [sym_bare_string] = ACTIONS(46),
    [anon_sym_LBRACK] = ACTIONS(49),
    [anon_sym_LBRACE] = ACTIONS(52),
  },
  [STATE(4)] = {
    [sym__scalar] = STATE(21),
    [sym_null_literal] = STATE(21),
    [sym_boolean_literal] = STATE(21),
    [sym_flow_sequence] = STATE(21),
    [sym_flow_mapping] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(55),
    [sym__newline] = ACTIONS(3),
    [sym_comment] = ACTIONS(55),
    [sym_mapping_key] = ACTIONS(55),
    [sym_sequence_indicator] = ACTIONS(57),
    [anon_sym_null] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [sym_float_literal] = ACTIONS(59),
    [sym_integer_literal] = ACTIONS(59),
    [sym_double_quoted_string] = ACTIONS(59),
    [sym_triple_quoted_string] = ACTIONS(61),
    [sym_bare_string] = ACTIONS(59),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(63),
    [sym__newline] = ACTIONS(3),
    [sym_comment] = ACTIONS(63),
    [sym_mapping_key] = ACTIONS(63),
    [sym_sequence_indicator] = ACTIONS(65),
    [anon_sym_null] = ACTIONS(65),
    [anon_sym_true] = ACTIONS(65),
    [anon_sym_false] = ACTIONS(65),
    [sym_float_literal] = ACTIONS(65),
    [sym_integer_literal] = ACTIONS(65),
    [sym_double_quoted_string] = ACTIONS(65),
    [sym_triple_quoted_string] = ACTIONS(63),
    [sym_bare_string] = ACTIONS(65),
    [anon_sym_LBRACK] = ACTIONS(63),
    [anon_sym_COMMA] = ACTIONS(63),
    [anon_sym_RBRACK] = ACTIONS(63),
    [anon_sym_LBRACE] = ACTIONS(63),
    [anon_sym_RBRACE] = ACTIONS(63),
  },
  [STATE(6)] = {
    [sym_mapping_pair] = STATE(22),
    [sym__scalar] = STATE(22),
    [sym_null_literal] = STATE(22),
    [sym_boolean_literal] = STATE(22),
    [sym_flow_sequence] = STATE(22),
    [sym_flow_mapping] = STATE(22),
    [sym__newline] = ACTIONS(3),
    [sym_mapping_key] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [sym_float_literal] = ACTIONS(67),
    [sym_integer_literal] = ACTIONS(67),
    [sym_double_quoted_string] = ACTIONS(67),
    [sym_triple_quoted_string] = ACTIONS(69),
    [sym_bare_string] = ACTIONS(67),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(71),
    [sym__newline] = ACTIONS(3),
    [sym_comment] = ACTIONS(71),
    [sym_mapping_key] = ACTIONS(71),
    [sym_sequence_indicator] = ACTIONS(73),
    [anon_sym_null] = ACTIONS(73),
    [anon_sym_true] = ACTIONS(73),
    [anon_sym_false] = ACTIONS(73),
    [sym_float_literal] = ACTIONS(73),
    [sym_integer_literal] = ACTIONS(73),
    [sym_double_quoted_string] = ACTIONS(73),
    [sym_triple_quoted_string] = ACTIONS(71),
    [sym_bare_string] = ACTIONS(73),
    [anon_sym_LBRACK] = ACTIONS(71),
    [anon_sym_COMMA] = ACTIONS(71),
    [anon_sym_RBRACK] = ACTIONS(71),
    [anon_sym_LBRACE] = ACTIONS(71),
    [anon_sym_RBRACE] = ACTIONS(71),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(75),
    [sym__newline] = ACTIONS(3),
    [sym_comment] = ACTIONS(75),
    [sym_mapping_key] = ACTIONS(75),
    [sym_sequence_indicator] = ACTIONS(77),
    [anon_sym_null] = ACTIONS(77),
    [anon_sym_true] = ACTIONS(77),
    [anon_sym_false] = ACTIONS(77),
    [sym_float_literal] = ACTIONS(77),
    [sym_integer_literal] = ACTIONS(77),
    [sym_double_quoted_string] = ACTIONS(77),
    [sym_triple_quoted_string] = ACTIONS(75),
    [sym_bare_string] = ACTIONS(77),
    [anon_sym_LBRACK] = ACTIONS(75),
    [anon_sym_COMMA] = ACTIONS(75),
    [anon_sym_RBRACK] = ACTIONS(75),
    [anon_sym_LBRACE] = ACTIONS(75),
    [anon_sym_RBRACE] = ACTIONS(75),
  },
  [STATE(9)] = {
    [sym_null_literal] = STATE(33),
    [sym_boolean_literal] = STATE(33),
    [sym_flow_sequence] = STATE(33),
    [sym_flow_mapping] = STATE(33),
    [sym__flow_value] = STATE(33),
    [sym__newline] = ACTIONS(3),
    [anon_sym_null] = ACTIONS(79),
    [anon_sym_true] = ACTIONS(81),
    [anon_sym_false] = ACTIONS(81),
    [sym_float_literal] = ACTIONS(83),
    [sym_integer_literal] = ACTIONS(85),
    [sym_double_quoted_string] = ACTIONS(85),
    [sym_triple_quoted_string] = ACTIONS(83),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(87),
    [anon_sym_LBRACE] = ACTIONS(21),
    [anon_sym_RBRACE] = ACTIONS(87),
    [sym_flow_bare_string] = ACTIONS(85),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(89),
    [sym__newline] = ACTIONS(3),
    [sym_comment] = ACTIONS(89),
    [sym_mapping_key] = ACTIONS(89),
    [sym_sequence_indicator] = ACTIONS(91),
    [anon_sym_null] = ACTIONS(91),
    [anon_sym_true] = ACTIONS(91),
    [anon_sym_false] = ACTIONS(91),
    [sym_float_literal] = ACTIONS(91),
    [sym_integer_literal] = ACTIONS(91),
    [sym_double_quoted_string] = ACTIONS(91),
    [sym_triple_quoted_string] = ACTIONS(89),
    [sym_bare_string] = ACTIONS(91),
    [anon_sym_LBRACK] = ACTIONS(89),
    [anon_sym_COMMA] = ACTIONS(89),
    [anon_sym_RBRACK] = ACTIONS(89),
    [anon_sym_LBRACE] = ACTIONS(89),
    [anon_sym_RBRACE] = ACTIONS(89),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(93),
    [sym__newline] = ACTIONS(3),
    [sym_comment] = ACTIONS(93),
    [sym_mapping_key] = ACTIONS(93),
    [sym_sequence_indicator] = ACTIONS(95),
    [anon_sym_null] = ACTIONS(95),
    [anon_sym_true] = ACTIONS(95),
    [anon_sym_false] = ACTIONS(95),
    [sym_float_literal] = ACTIONS(95),
    [sym_integer_literal] = ACTIONS(95),
    [sym_double_quoted_string] = ACTIONS(95),
    [sym_triple_quoted_string] = ACTIONS(93),
    [sym_bare_string] = ACTIONS(95),
    [anon_sym_LBRACK] = ACTIONS(93),
    [anon_sym_COMMA] = ACTIONS(93),
    [anon_sym_RBRACK] = ACTIONS(93),
    [anon_sym_LBRACE] = ACTIONS(93),
    [anon_sym_RBRACE] = ACTIONS(93),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(97),
    [sym__newline] = ACTIONS(3),
    [sym_comment] = ACTIONS(97),
    [sym_mapping_key] = ACTIONS(97),
    [sym_sequence_indicator] = ACTIONS(99),
    [anon_sym_null] = ACTIONS(99),
    [anon_sym_true] = ACTIONS(99),
    [anon_sym_false] = ACTIONS(99),
    [sym_float_literal] = ACTIONS(99),
    [sym_integer_literal] = ACTIONS(99),
    [sym_double_quoted_string] = ACTIONS(99),
    [sym_triple_quoted_string] = ACTIONS(97),
    [sym_bare_string] = ACTIONS(99),
    [anon_sym_LBRACK] = ACTIONS(97),
    [anon_sym_COMMA] = ACTIONS(97),
    [anon_sym_RBRACK] = ACTIONS(97),
    [anon_sym_LBRACE] = ACTIONS(97),
    [anon_sym_RBRACE] = ACTIONS(97),
  },
  [STATE(13)] = {
    [ts_builtin_sym_end] = ACTIONS(101),
    [sym__newline] = ACTIONS(3),
    [sym_comment] = ACTIONS(101),
    [sym_mapping_key] = ACTIONS(101),
    [sym_sequence_indicator] = ACTIONS(103),
    [anon_sym_null] = ACTIONS(103),
    [anon_sym_true] = ACTIONS(103),
    [anon_sym_false] = ACTIONS(103),
    [sym_float_literal] = ACTIONS(103),
    [sym_integer_literal] = ACTIONS(103),
    [sym_double_quoted_string] = ACTIONS(103),
    [sym_triple_quoted_string] = ACTIONS(101),
    [sym_bare_string] = ACTIONS(103),
    [anon_sym_LBRACK] = ACTIONS(101),
    [anon_sym_COMMA] = ACTIONS(101),
    [anon_sym_RBRACK] = ACTIONS(101),
    [anon_sym_LBRACE] = ACTIONS(101),
    [anon_sym_RBRACE] = ACTIONS(101),
  },
  [STATE(14)] = {
    [ts_builtin_sym_end] = ACTIONS(105),
    [sym__newline] = ACTIONS(3),
    [sym_comment] = ACTIONS(105),
    [sym_mapping_key] = ACTIONS(105),
    [sym_sequence_indicator] = ACTIONS(107),
    [anon_sym_null] = ACTIONS(107),
    [anon_sym_true] = ACTIONS(107),
    [anon_sym_false] = ACTIONS(107),
    [sym_float_literal] = ACTIONS(107),
    [sym_integer_literal] = ACTIONS(107),
    [sym_double_quoted_string] = ACTIONS(107),
    [sym_triple_quoted_string] = ACTIONS(105),
    [sym_bare_string] = ACTIONS(107),
    [anon_sym_LBRACK] = ACTIONS(105),
    [anon_sym_COMMA] = ACTIONS(105),
    [anon_sym_RBRACK] = ACTIONS(105),
    [anon_sym_LBRACE] = ACTIONS(105),
    [anon_sym_RBRACE] = ACTIONS(105),
  },
  [STATE(15)] = {
    [ts_builtin_sym_end] = ACTIONS(109),
    [sym__newline] = ACTIONS(3),
    [sym_comment] = ACTIONS(109),
    [sym_mapping_key] = ACTIONS(109),
    [sym_sequence_indicator] = ACTIONS(111),
    [anon_sym_null] = ACTIONS(111),
    [anon_sym_true] = ACTIONS(111),
    [anon_sym_false] = ACTIONS(111),
    [sym_float_literal] = ACTIONS(111),
    [sym_integer_literal] = ACTIONS(111),
    [sym_double_quoted_string] = ACTIONS(111),
    [sym_triple_quoted_string] = ACTIONS(109),
    [sym_bare_string] = ACTIONS(111),
    [anon_sym_LBRACK] = ACTIONS(109),
    [anon_sym_COMMA] = ACTIONS(109),
    [anon_sym_RBRACK] = ACTIONS(109),
    [anon_sym_LBRACE] = ACTIONS(109),
    [anon_sym_RBRACE] = ACTIONS(109),
  },
  [STATE(16)] = {
    [ts_builtin_sym_end] = ACTIONS(113),
    [sym__newline] = ACTIONS(3),
    [sym_comment] = ACTIONS(113),
    [sym_mapping_key] = ACTIONS(113),
    [sym_sequence_indicator] = ACTIONS(115),
    [anon_sym_null] = ACTIONS(115),
    [anon_sym_true] = ACTIONS(115),
    [anon_sym_false] = ACTIONS(115),
    [sym_float_literal] = ACTIONS(115),
    [sym_integer_literal] = ACTIONS(115),
    [sym_double_quoted_string] = ACTIONS(115),
    [sym_triple_quoted_string] = ACTIONS(113),
    [sym_bare_string] = ACTIONS(115),
    [anon_sym_LBRACK] = ACTIONS(113),
    [anon_sym_COMMA] = ACTIONS(113),
    [anon_sym_RBRACK] = ACTIONS(113),
    [anon_sym_LBRACE] = ACTIONS(113),
    [anon_sym_RBRACE] = ACTIONS(113),
  },
  [STATE(17)] = {
    [sym_null_literal] = STATE(25),
    [sym_boolean_literal] = STATE(25),
    [sym_flow_sequence] = STATE(25),
    [sym_flow_mapping] = STATE(25),
    [sym__flow_value] = STATE(25),
    [sym__newline] = ACTIONS(3),
    [anon_sym_null] = ACTIONS(79),
    [anon_sym_true] = ACTIONS(81),
    [anon_sym_false] = ACTIONS(81),
    [sym_float_literal] = ACTIONS(117),
    [sym_integer_literal] = ACTIONS(119),
    [sym_double_quoted_string] = ACTIONS(119),
    [sym_triple_quoted_string] = ACTIONS(117),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_RBRACK] = ACTIONS(121),
    [anon_sym_LBRACE] = ACTIONS(21),
    [sym_flow_bare_string] = ACTIONS(119),
  },
  [STATE(18)] = {
    [sym_null_literal] = STATE(32),
    [sym_boolean_literal] = STATE(32),
    [sym_flow_sequence] = STATE(32),
    [sym_flow_mapping] = STATE(32),
    [sym__flow_value] = STATE(32),
    [sym__newline] = ACTIONS(3),
    [anon_sym_null] = ACTIONS(79),
    [anon_sym_true] = ACTIONS(81),
    [anon_sym_false] = ACTIONS(81),
    [sym_float_literal] = ACTIONS(123),
    [sym_integer_literal] = ACTIONS(125),
    [sym_double_quoted_string] = ACTIONS(125),
    [sym_triple_quoted_string] = ACTIONS(123),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_RBRACK] = ACTIONS(127),
    [anon_sym_LBRACE] = ACTIONS(21),
    [sym_flow_bare_string] = ACTIONS(125),
  },
  [STATE(19)] = {
    [sym_null_literal] = STATE(32),
    [sym_boolean_literal] = STATE(32),
    [sym_flow_sequence] = STATE(32),
    [sym_flow_mapping] = STATE(32),
    [sym__flow_value] = STATE(32),
    [sym__newline] = ACTIONS(3),
    [anon_sym_null] = ACTIONS(79),
    [anon_sym_true] = ACTIONS(81),
    [anon_sym_false] = ACTIONS(81),
    [sym_float_literal] = ACTIONS(123),
    [sym_integer_literal] = ACTIONS(125),
    [sym_double_quoted_string] = ACTIONS(125),
    [sym_triple_quoted_string] = ACTIONS(123),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_RBRACK] = ACTIONS(129),
    [anon_sym_LBRACE] = ACTIONS(21),
    [sym_flow_bare_string] = ACTIONS(125),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(79), 1,
      anon_sym_null,
    ACTIONS(81), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(123), 2,
      sym_float_literal,
      sym_triple_quoted_string,
    ACTIONS(125), 3,
      sym_integer_literal,
      sym_double_quoted_string,
      sym_flow_bare_string,
    STATE(32), 5,
      sym_null_literal,
      sym_boolean_literal,
      sym_flow_sequence,
      sym_flow_mapping,
      sym__flow_value,
  [33] = 3,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(131), 6,
      ts_builtin_sym_end,
      sym_comment,
      sym_mapping_key,
      sym_triple_quoted_string,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
    ACTIONS(133), 8,
      sym_sequence_indicator,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_float_literal,
      sym_integer_literal,
      sym_double_quoted_string,
      sym_bare_string,
  [55] = 3,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(135), 6,
      ts_builtin_sym_end,
      sym_comment,
      sym_mapping_key,
      sym_triple_quoted_string,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
    ACTIONS(137), 8,
      sym_sequence_indicator,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_float_literal,
      sym_integer_literal,
      sym_double_quoted_string,
      sym_bare_string,
  [77] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(139), 1,
      anon_sym_COMMA,
    ACTIONS(142), 1,
      anon_sym_RBRACK,
    STATE(23), 1,
      aux_sym_flow_sequence_repeat1,
  [90] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(144), 1,
      anon_sym_COMMA,
    ACTIONS(146), 1,
      anon_sym_RBRACE,
    STATE(27), 1,
      aux_sym_flow_mapping_repeat1,
  [103] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(148), 1,
      anon_sym_COMMA,
    ACTIONS(150), 1,
      anon_sym_RBRACK,
    STATE(29), 1,
      aux_sym_flow_sequence_repeat1,
  [116] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(152), 1,
      sym_mapping_key,
    ACTIONS(154), 1,
      anon_sym_RBRACE,
    STATE(28), 1,
      sym_flow_pair,
  [129] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    ACTIONS(159), 1,
      anon_sym_RBRACE,
    STATE(27), 1,
      aux_sym_flow_mapping_repeat1,
  [142] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(161), 1,
      anon_sym_COMMA,
    ACTIONS(163), 1,
      anon_sym_RBRACE,
    STATE(24), 1,
      aux_sym_flow_mapping_repeat1,
  [155] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(127), 1,
      anon_sym_RBRACK,
    ACTIONS(165), 1,
      anon_sym_COMMA,
    STATE(23), 1,
      aux_sym_flow_sequence_repeat1,
  [168] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(146), 1,
      anon_sym_RBRACE,
    ACTIONS(152), 1,
      sym_mapping_key,
    STATE(34), 1,
      sym_flow_pair,
  [181] = 4,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(152), 1,
      sym_mapping_key,
    ACTIONS(167), 1,
      anon_sym_RBRACE,
    STATE(34), 1,
      sym_flow_pair,
  [194] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(142), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [202] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(169), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [210] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(159), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [218] = 3,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(152), 1,
      sym_mapping_key,
    STATE(34), 1,
      sym_flow_pair,
  [228] = 2,
    ACTIONS(3), 1,
      sym__newline,
    ACTIONS(171), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(20)] = 0,
  [SMALL_STATE(21)] = 33,
  [SMALL_STATE(22)] = 55,
  [SMALL_STATE(23)] = 77,
  [SMALL_STATE(24)] = 90,
  [SMALL_STATE(25)] = 103,
  [SMALL_STATE(26)] = 116,
  [SMALL_STATE(27)] = 129,
  [SMALL_STATE(28)] = 142,
  [SMALL_STATE(29)] = 155,
  [SMALL_STATE(30)] = 168,
  [SMALL_STATE(31)] = 181,
  [SMALL_STATE(32)] = 194,
  [SMALL_STATE(33)] = 202,
  [SMALL_STATE(34)] = 210,
  [SMALL_STATE(35)] = 218,
  [SMALL_STATE(36)] = 228,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mapping_pair, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mapping_pair, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_null_literal, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_null_literal, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_sequence, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_flow_sequence, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_pair, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_sequence, 4, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_flow_sequence, 4, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_sequence, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_flow_sequence, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_mapping, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_flow_mapping, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_mapping, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_flow_mapping, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_mapping, 4, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_flow_mapping, 4, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_sequence, 5, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_flow_sequence, 5, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_mapping, 5, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_flow_mapping, 5, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mapping_pair, 2, 0, 1),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mapping_pair, 2, 0, 1),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence_entry, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sequence_entry, 2, 0, 0),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_flow_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_flow_sequence_repeat1, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_flow_mapping_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_flow_mapping_repeat1, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flow_pair, 2, 0, 1),
  [171] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ayml(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ayml",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
